---
title: "Capacitaciones"
description: |
  Videos y presentaciones utilizadas en las sesiones de capacitación realizadas en 2021. Las mismas se dividen en dos modulos: (1) Propuestas Metodológicas y Definiciones y (2) Ciencia de Datos para el Turismo 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Propuestas Metodológicas y Definiciones

### Documento Técnico \#1: Conceptos y elementos básicos para la medición provincial de los turistas

<iframe width="560" height="315" src="https://www.youtube.com/embed/SgUjiOcxyxI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>

</iframe>

#### Presentaciones

 [Conceptos y Elementos para la Medición Provincial de los Turistas](https://github.com/dnme-minturdep/armonizacion/raw/master/man/1.1_conceptos-elementos-para-la-medicio%CC%81n.pdf) 

 [Sistema de Estadística de Turismo en la Argentina](https://github.com/dnme-minturdep/armonizacion/raw/master/man/1.2_sistema-estadistica-de-turismo.pdf) 

### Documento Técnico \#2: Propuestas metodológicas para las encuestas de ocupación en alojamientos turísticos

<iframe width="560" height="315" src="https://www.youtube.com/embed/3t7umC-c9bc" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>

</iframe>

#### Presentaciones

 [Encuestas de Ocupación](https://github.com/dnme-minturdep/armonizacion/raw/master/man/2.1_Estudios_alojamieto.pdf) 

 [Encuesta de Ocupación Hotelera (EOH)](https://github.com/dnme-minturdep/armonizacion/raw/master/man/2.2_EOH.pdf) 

### Documento Técnico \#3: Descripción, análisis y utilización de los Registros Administrativos para la medición del Turismo

<iframe width="560" height="315" src="https://www.youtube.com/embed/dQEFXqjZM-U" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>

</iframe>

#### Presentaciones

 [Uso de los Registros Adminsitrativos para la Medición del Turismo](https://github.com/dnme-minturdep/armonizacion/raw/master/man/3.1_Usos%20de%20los%20registros%20adm.pdf) 

 [Parques Nacionales](https://github.com/dnme-minturdep/armonizacion/raw/master/man/3.3_PN.pdf) 

 [Padrón nico de Alojamiento (PUNA)](https://github.com/dnme-minturdep/armonizacion/raw/master/man/1.2_sistema-estadistica-de-turismo.pdf) 

 [Transito Vehícular](https://github.com/dnme-minturdep/armonizacion/raw/master/man/3.4_peajes.pdf) 

 [Conectividad Aerocomercial](https://github.com/dnme-minturdep/armonizacion/raw/master/man/3.5_CONECTIVIDAD%20AEROCOMERCIAL.pdf) 

 [Migraciones](https://github.com/dnme-minturdep/armonizacion/raw/master/man/3.6_Turismo_internacional.pdf) 

### Documento Técnico \#4: Propuestas Metodológicas para las Encuestas de Perfil del Visitante

<iframe width="560" height="315" src="https://www.youtube.com/embed/ePhemV6WsLQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>

</iframe>

#### Presentaciones

 [Encuestas de Perfil de Visitante](https://github.com/dnme-minturdep/armonizacion/raw/master/man/4.1_EncuestasPerfilVisitante.pdf) 

 [Encuesta de Turismo Internacional (ETI)](https://github.com/dnme-minturdep/armonizacion/raw/master/man/4.2_ETI%20y%20EVyTH.pdf) 

### Documento Técnico \#5: Medición de la contribución económica del turismo: actividad y empleo

<iframe width="560" height="315" src="https://www.youtube.com/embed/wXNlFGQi0PM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>

</iframe>

#### Presentaciones

 [Medición de la Contribución Económica del Turismo: Actividad y Empleo](https://github.com/dnme-minturdep/armonizacion/raw/master/man/5.1_Medicio%CC%81n%20de%20la%20contribucio%CC%81n.pdf) 

 [Fuentes de Infomración](https://github.com/dnme-minturdep/armonizacion/raw/master/man/5.2_Fuentes%20de%20Informacio%CC%81n.pdf) 


## Ciencia de Datos para el Turismo

4 sesiones en las que se introduce el lenguaje de programación R como la caja de herramientas para poder llevar adelante cada tarea y etapa del análisis de datos. 


###  [Documento Técnico \#6](https://dnme-minturdep.github.io/DT6_ciencia_de_datos_turismo/) 


### Sesión 1: Intro a R, Proyectos, Rmarkdown y lectura de datos

<iframe width="560" height="315" src="https://www.youtube.com/embed/1OjTm3NLIs8" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### Sesión 2: Intro a Manipulación de datos y Visualización  

<iframe width="560" height="315" src="https://www.youtube.com/embed/35E9ChlK50Y" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### Sesión 3: Manipulación de datos ordenados y Visualización con ggplot2

<iframe width="560" height="315" src="https://www.youtube.com/embed/O4YC5dlH88A" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


### Sesión 4: Tablas, apariencia de gráficos 

<iframe width="560" height="315" src="https://www.youtube.com/embed/jm8j4rZPkQ8" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
