---
title: "Difusión de Publicaciones"
description: "Se presenta aquí el conjunto de publicaciones que realiza la Dirección Nacional de Mercados y Estadística de la Subsecretaría de Desarrollo Estratégico del [Ministerio de Turismo y Deportes](http://turismo.gob.ar/ 'MINTURDEP')."
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r}
### Cargo librerías
install.packages("devtools")
install.packages("tidyverse")
install.packages("lubridate")
install.packages("toastui")
install.packages("shiny")
#install.packages("googlesheets4")
devtools::install_github("dnme-minturdep/comunicacion")

library(tidyverse)
library(lubridate)
library(toastui)
library(shiny)
library(comunicacion)
```


```{r}
### Importar calendario fuente
# Desactivo pedido de acceso
googlesheets4::gs4_deauth()

# Traigo base de calendario
base <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/11nyQ5QwuTUaS6F_g8ZM6Ta9SXnrOiCtPV3h2rG_LVV0/edit?usp=sharing")


### Limpieza de base
calendario <- base %>% 
  rename(title    = titulo, 
         body     = descripcion) %>% 
  mutate(start      = ymd(paste(anio, mes, dia, sep = "-")),
         end        = start,
         category   = "allday",
         calendarId = 123) %>% 
  select(title, body, category, start, end, calendarId)

```


```{r, echo = FALSE}
publicados <- base %>% filter(if_any(.cos = everything(), 
                       .fns = ~ !is.na(.))) %>% 
  nrow() %>% 
  as_tibble()

write_csv(x = publicados, ".github/data/n_published.csv")

```



```{r}
### Armo calendario
calendar(
  navigation = TRUE,
  navOpts = navigation_options(
    today_label = "Hoy",
    class = "bttn-stretch bttn-sm bttn-warning",
    color = dnmye_colores("gris oscuro"), 
    fmt_date = format("MM/YYYY"),
    sep_date = "-"
  )
) %>%
  cal_month_options(
    startDayOfWeek = 7,
    daynames = 
      #c("Dom", "Lun", "Mar", "Mie", "Jue", "Vie", "Sab"),
      c("D", "L", "M", "M", "J", "V", "S"),
    narrowWeekend = TRUE,
    isAlways6Week = F
  ) %>%
  cal_schedules(
    calendario
    ) %>% 
  cal_props(
    id = 123,
    color = comunicacion::dnmye_colores("cian"),
    bgColor = "white",
    borderColor = comunicacion::dnmye_colores("rosa")
    )
      

```


