on:
 schedule:
   - cron:  "0 21 * * 0-6"
 workflow_dispatch:

name: check_calendar_flow

jobs:
  run-r-script:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v1
        with:
          use-public-rspm: true
          
      - name: Execute calendar check updates and deploy
        run: |
          Rscript ".github/source/check_calendar_items.R"
          
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m "Actualizo eventos en calendario" || echo "No changes to commit"
          git push origin || echo "No changes to commit"
