on:
 schedule:
   - cron:  "0 19 * * 1-5"
 workflow_dispatch:

name: check_calendar_flow

jobs:
  run-r-script:
    runs-on: macos-latest
    timeout-minutes: 30
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      
      - uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@master

      - name: Install dependencies
        run: |
          install.packages("rmarkdown")
          install.packages("distill")
          install.packages("googlesheets4")
          install.packages("tidyverse")
          install.packages("toastui")

      - name: Correr script calendar
        run: |
          Rscript ".github/source/check_calendar_items.R"
          
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m "Actualizo eventos en calendario" || echo "No changes to commit"
          git push origin || echo "No changes to commit"
