on:
 schedule:
   - cron:  "0 21 * * 0-6"
 workflow_dispatch:

name: check_calendar_flow

jobs:
  run-r-script:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      
      - name: Install dependencies
        run: |
          install.packages("rmarkdown")
          install.packages("distill")
        
      - name: Render rmd
        run: Rscript -e 'rmarkdown::render(input = "index.Rmd", output_yaml = "_site.yml")'
          
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m "Actualizo eventos en calendario" || echo "No changes to commit"
          git push origin || echo "No changes to commit"
